version: "3.8"

services:
  postgres:
    image: postgres:alpine
    restart: always
    volumes:
      - ./postgresql/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: hh
      POSTGRES_USER: hh
      POSTGRES_PASSWORD: hh
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U hh"]
      interval: 10s
      timeout: 5s
      retries: 5
#  todo-app:
#    build: .
#    container_name: app
#    ports:
#      - "8080:8080"
#    depends_on:
#      postgres:
#        condition: service_healthy
#    environment:
#      - SPRING_DATASOURCE_URL=jdbc:postgresql://localhost:5432/hh
#      - POSTGRES_USER=hh
#      - POSTGRES_PASSWORD=hh
